#+title: List of Problems I Couldn't Solve

\newpage

- [ ] Dynamic Programming
- [ ] Maximum Subarry Problem
- [ ] Path sums
- [ ] Djikstra's Algorithm
- [ ] Tiling problems


* ZIO2003
** 5: Number of Graph Paths
Komal, Narain and Robert all work in the same office. All the roads in the city where
they live are one-way and their route from home to office must take this into account.
Here is a map of the city. The letters K, N and R mark the homes of Komal, Narain
and Robert, respectively, and O marks the office where they work. The direction in
which each road can be used is indicated by an arrow. For each person, calculate how
many different routes that person can take from home to office.

* ZIO2005
** 1: Rings of Unconnected DAGs
The director of Hind Circus has decided to add a new performance called the monkey
dance to his show. The monkey dance is danced simultaneously by N monkeys.
There are N circles drawn on the ground. There are N arrows drawn between the
circles in such a way that for each circle, exactly one arrow begins at that circle and
exactly one arrow ends at that circle. No arrow can both begin and end at the same
circle.
When the show begins, each monkey sits on a different circle. At each whistle of the
ringmaster, all the monkeys simultaneously jump from one circle to the next, following
the arrow leading out of the current circle. This is one step of the dance. The dance
ends when all the monkeys have simultaneously returned to the circles where they
initially started.
The director wishes the dance to last as many steps as possible. This can be achieved
by drawing the arrows intelligently.
For each of the three values of N given below, what is the maximum number of steps
that the monkey dance can be made to last by drawing arrows appropriately?

** 3, 4: Dynamic Programming

There is a unique sequence of positive numbers that starts with the number 1 at the
first position and has the following properties.
• Each value in the sequence is greater than or equal to every value that appears
earlier in the sequence.
• If the value at position k in the sequence is m, then the number k appears exactly
m times in the sequence.\\

A teacher assigns homework at the beginning of the first day of class. Each homework
problem carries one mark, plus a bonus if submitted within a specified number of days.
Each homework problem takes exactly one day to complete.
The deadline for earning the bonus and the number of bonus marks are different for
each homework problem. For instance, if a problem has a deadline of 6 days and carries
bonus 10 marks, then it earns 10 bonus marks provided it is submitted before the end
of the 6th day.

* ZIO2006
* ZIO2007
* ZIO2008
None.

* ZIO2009
** Tiling Problem
You have to tile a room that is two units wide and N units long. You have with you two
types of tiles: a rectangle that is one unit wide and two units long, and an L-shaped
tile covering three square units. Here are pictures of the two types of tiles.
You are allowed to rotate the tiles when you lay them. You have an infinite supply
of both types of tiles. However, your architect is from Nauru and is a believer in the
Polynesian system of tiling called Batlar Guntu which forbids any corner where four
tiles meet.
For instance, here are some ways to tile a 2 × 4 room. The first three are consistent
with the Batlar Guntu system while the fourth tiling is not.

** Path sums: DP, Writing Recurrence Relations
https://discuss.codechef.com/t/zio09002-editorial/52659
